### ISSUE TITLE
I can’t open the app.

### ISSUE THREAD

**Issue by Kami1589** [Lakr233/NotchDrop#1]
I held the Control key, clicked the app, then selected Open, but it still won't open, and reinstalling still doesn't work.

MacBook Pro, 13-inch, M2, 2022  , 16 GB  , Sonoma 14.5

I am very interested in this app, so please update it.

**Comment by tkgka** [comment]
@Kami1589 
what I check from the source code, this application does not allowed to use on macBook which doesn't have notch,
so if you want to use application, fix the code like under below

Appdelegate line 38
```swift
//        guard let mainScreen = NSScreen.buildin, mainScreen.notchSize != .zero else { // fix this line
guard let mainScreen = NSScreen.buildin else {
```
NotchWindowController line 20
```swift

//        vm.deviceNotchRect = CGRect( // fix this line
//            x: screen.frame.origin.x + (screen.frame.width - notchSize.width) / 2,
//            y: screen.frame.origin.y + screen.frame.height - notchSize.height,
//            width: notchSize.width,
//            height: notchSize.height
//        )

vm.deviceNotchRect = .init(x: -1060, y: 1340, width: 150, height: notchHeight) // you should change the x and y value for your screen
```
