### ISSUE TITLE
NotchDrop abnormal pop-up

### ISSUE THREAD

**Issue by YYshen07** [Lakr233/NotchDrop#17]
My Notchdrop will pop up abnormally when I use a parallel desktop, and sometimes it will pop up abnormally when the computer is in a high-power state.I am trying to reproduce the bug and show it to you.

**Comment by Lakr233** [comment]
Does the bug still exists?

**Comment by Lakr233** [comment]
We have changed the way about how and when the notch will open, should be fixed.
