### ISSUE TITLE
Why named this Chinese name?

### ISSUE THREAD

**Issue by DanielDeng3** [Lakr233/NotchDrop#20]
this is interesting app , but this name ,it's sucks on my opinion.
maybe call '随日存, 一日照，简放岛，‘ or other simple chinese word is better.
by the way i will to learn how to put app to homebrew repository. i will help you do this for no charge.

**Comment by Lakr233** [comment]
哈哈哈哈哈哈哈因为脑子一热就这么起名了 用着吧 我不想改了 你可以打一个你自己的包

**Comment by Lakr233** [comment]
Done #31
