### ISSUE TITLE
刘海外缘挡住鼠标点击Safari的Tab

### ISSUE THREAD

**Issue by tychoon** [Lakr233/NotchDrop#23]
请见录屏视频，Safari全屏时，刘海外缘的响应区域会遮挡，导致无法点选下面的Tab页面。
https://github.com/user-attachments/assets/2ac31210-4e2d-42ff-a8a5-3f65bb5fb3f3

**Comment by Feliks151450** [comment]
非刘海的屏幕都会挡，希望能优化

**Comment by Lakr233** [comment]
后面要不还是把没有刘海的显示器的支持给关了吧。。。

**Comment by Lakr233** [comment]
我不打算做多显示器相关的需求和修复了 用户配置很多 我只保证我自己的需求完成 一天吵到晚给我弄烦了

你们要是有想法 可以自己做一下 提过来合并请求我会合 但是除此之外不做计划和安排
