### ISSUE TITLE
与fcp有冲突。会使触控板异常震动

### ISSUE THREAD

**Issue by Balllbing** [Lakr233/NotchDrop#25]
就是如果同时打开fcp和这个app之后会时不时出现触控板自己震动，特别是fcp卡住（任务量大）的时候这个特别明显，严重时会导致fcp无响应，关闭app之后就没这个问题了，希望能得到帮助解决这个问题，因为真的很需要这两个软件同时存在并运行，对于剪视频会哟很大的帮助～～～～～～～

**Comment by Lakr233** [comment]
这个很神奇 我也在用 fcp 但是貌似没遇到。。。按道理他们不会打架才对

**Comment by Balllbing** [comment]
> 这个很神奇 我也在用 fcp 但是貌似没遇到。。。按道理他们不会打架才对

今天又试了一下发现不但是fcp ，我打开lr的时候刚开始也震了，就是正在打开lr的时候正在加载和刚进去几秒的时候震的，但是其他微信啊b站啊倒不会（ps还没试过）
ps：补充一下很神奇的是只要震了一般都会卡（震是那种把鼠标指针移到隐藏着的app的时候的那种震，就是把鼠标移到刘海屏那个触控板会稍稍震一下的那种震，但是是一直震）

**Comment by Balllbing** [comment]
> 这个很神奇 我也在用 fcp 但是貌似没遇到。。。按道理他们不会打架才对

我刚刚尝试了删了重下，问题依然存在（包括关闭fcp，fcp正在渲染较重任务中），会不会是我的M3 pro的原因呢？

**Comment by Balllbing** [comment]
好的，有新状况我就回报，真的很好用你的这个，加油哇～～

**Comment by stu00608** [comment]
我自己在正常使用時也很常遇到，目前使用M2 Mackbook Air 13inch
還找不太到規律，但感覺是會在特定條件下觸發！

**Comment by Lakr233** [comment]
看下新版本是不是修好了这个问题

**Comment by Balllbing** [comment]
> 看下新版本是不是修好了这个问题

好的，我试试    等我出结果的，辛苦你了大佬～～！
