### ISSUE TITLE
外接显示器时隐藏

### ISSUE THREAD

**Issue by yzlnew** [Lakr233/NotchDrop#26]
在没有刘海的外接显示器上隐藏或者换一种处理方式？

**Comment by Lakr233** [comment]
之前是不支持外接显示器 但是群友一直要 就给上了一版。。。众口难调啊 看看后面要不要做一个开关吧

**Comment by yzlnew** [comment]
外接显示器还是刚需吧，可以在无刘海显示屏上实现类似 yoink 那种效果？
目前是这样的，有点尴尬😅
![image](https://github.com/user-attachments/assets/24b29d7e-ab2c-4ae9-8718-4a7663737cd2)

**Comment by Lakr233** [comment]
外接显示器你最好是找个你认识的人给你白嫖不然我用不到我不打算做需求或者修改他的表现形式。

**Comment by yzlnew** [comment]
感谢。简单看了下，把下面的 0.3 改成 0 就符合需求了，有同样需要的可以自己编译下。

https://github.com/Lakr233/NotchDrop/blob/287f54507e9883be77d4ae8ae9a08e42dfcb00bd/NotchDrop/NotchView.swift#L48
