### ISSUE TITLE
Airdrop not working

### ISSUE THREAD

**Issue by short24112** [Lakr233/NotchDrop#28]
Airdrop not working ;(
![Screenshot 2024-07-29 at 18 08 38](https://github.com/user-attachments/assets/0e12e0dc-21d6-428e-84b9-3690cbb5185d)

**Comment by Lakr233** [comment]
You may denied a pop up permission alert. :(
Otherwise I dont know why.

**Comment by short24112** [comment]
> You may denied a pop up permission alert. :( Otherwise I dont know why.

I’ve reinstalled, and it’s works perfectly:)
Thanks for creating free version of the NotchNook
