### ISSUE TITLE
能一起开发嘛

### ISSUE THREAD

**Issue by bugsmachine** [Lakr233/NotchDrop#29]
大学生放假了有点闲哈哈哈哈，挺喜欢notch drop的。我看之前的issues里有说语言设置和文件保存时常设置的，我就自己做了一版。
<img width="595" alt="image" src="https://github.com/user-attachments/assets/9a21db68-588d-4bd6-be8b-9089a35898c2">

语言搞的差不多了可以跟随系统设置也可以自己选（也就那三个选项哈哈哈）保存时间还没研究透楼主的代码哈哈哈哈研究透了再写😜

想问下楼主如果性能OK需求合理可以merge嘛

**Comment by Lakr233** [comment]
搞啊 只要是通用需求都能合的！

**Comment by bugsmachine** [comment]
ok ok 🥰

**Comment by bugsmachine** [comment]
@Lakr233 搞好了哥，加上了开机自启动，语言设置和文件保存时间设置，fire PR 了，我自己测试了一天没啥问题。细节和效果图在merge request 里应该能看到。感觉现在很完美了哈哈哈哈

哥你觉着这玩意加上云存储能玩吗就是把类似于百度网盘的悬浮球集成在这上面

**Comment by 1234scarecrow** [comment]
哥，咱也用了好多天，但是觉得是不是可以加一个设置，显示哪些功能，目前只用到airdrop。但是拖过去只有一小块是airdrop的。如果能只显示AirDrop区域就会好用很多，目前我自己也在学swift UI。哥你没时间的话我可以自己试试整一整

**Comment by Lakr233** [comment]
Merged. Thanks
