### ISSUE TITLE
Cannot drag files from the [Downloads] folder in the Dock

### ISSUE THREAD

**Issue by Emrys365** [Lakr233/NotchDrop#3]
macOS version: 14.5 (23F79), Apple M3 Pro

Description:

![CleanShot 2024-07-08 at 13 12 01](https://github.com/Lakr233/NotchDrop/assets/18532145/051f48a9-0429-4b7a-9000-b4d93f391326)

**Comment by Lakr233** [comment]
Drag and drop isn’t very easy to fix, but I’ll keep an eye on it. 🫠

**Comment by Lakr233** [comment]
Sorry, failed to fix.
