### ISSUE TITLE
无法隔空投送

### ISSUE THREAD

**Issue by THREECATSSS** [Lakr233/NotchDrop#30]
如题，无法隔空投送，提示如下“AirDrop service not available”
<img width="260" alt="iShot_2024-07-30_16 41 33" src="https://github.com/user-attachments/assets/bde2ada3-1538-4cf9-a6d1-7f583019d413">

系统版本mac os14.5，芯片m3 pro，软件版本号2.2，自测系统airdrop功能正常运行，但是拖动进刘海的时候无法airdrop，大佬可以看下吗

**Comment by Lakr233** [comment]
你拒绝了一个权限 重新安装可解。

https://github.com/Lakr233/NotchDrop/issues/28

**Comment by THREECATSSS** [comment]
解决了，十分感谢~
BTW，这个软件真的好好看而且好实用，很喜欢，感谢付出~
