### ISSUE TITLE
文件无法从简放岛拖放到微信

### ISSUE THREAD

**Issue by poneding** [Lakr233/NotchDrop#32]
如题：文件无法从简放岛拖放到微信

拖放过去只会在输入框中填入文件路径。

![Kapture 2024-07-31 at 15 27 02](https://github.com/user-attachments/assets/caadbb8e-4ac8-4ff5-bb7d-cb6f8b02f34d)

**Comment by Lakr233** [comment]
草 可能被改坏了 我记得我特别适配过的

**Comment by Lakr233** [comment]
短时间没精力看啦 晚点下次有 PR 我看看是不是一起修了
