### ISSUE TITLE
桌面目录随意拖动会消失

### ISSUE THREAD

**Issue by mullermyp-edu** [Lakr233/NotchDrop#33]
桌面放的目录文件，随便拖几下就不见了，但在desktop目录里还存在。
关闭程序，重启 finder后就恢复了。

**Comment by Lakr233** [comment]
看起来像是 macOS 的问题？

**Comment by mullermyp-edu** [comment]
> 看起来像是 macOS 的问题？

macos 14.2 
Mbp2021 14寸
NorthDrop 不打开就没这个问题，是和什么软件或者配置冲突了吗？

**Comment by Lakr233** [comment]
也不是没可能 鼠标松开的时候会清空拖拽的剪贴板 可能有冲突 后面我看看咋搞吧

**Comment by Lakr233** [comment]
Should be fixed.
