### ISSUE TITLE
保留的文件夹可以改成单击打开吗？

### ISSUE THREAD

**Issue by laivn** [Lakr233/NotchDrop#34]
保留的文件夹目前是双击打开，可以改成单击打开吗？
另外建议增加一个自动弹出的选项，现在需要点击刘海才弹出

**Comment by Lakr233** [comment]
不考虑增加单机打开 不考虑自动弹出 你可以自己动手

**Comment by Lakr233** [comment]
被你忽悠了 现在就是单机打开 可能是有其他软件抢了我们的焦点 这个我没法解决a

**Comment by laivn** [comment]
🤣估计是iStat Menus抢的触发焦点
