### ISSUE TITLE
NotchDrop causing files to disappear when using Sort By > Snap To Grid 

### ISSUE THREAD

**Issue by PatJackAttack** [Lakr233/NotchDrop#37]
Right-clicking on the desktop or within Finder and using "Sort By > Snap To Grid" in macOS 17.6 is causing issues where files disappear while using NotchDrop. When you switch to a different folder and then return to the folder where the files disappeared, they are shown again. 

Issue disappears when NotchDrop is closed. A video demonstrating this bug is attached:

https://github.com/user-attachments/assets/d42dfb39-bf82-416b-8246-7114e0dd80c3

**Comment by Lakr233** [comment]
Does this issue stay after 2.4 build 16? Or exists with the AppStore version?

**Comment by Lakr233** [comment]
Close due to no no longer reproducible. Reopen if needed.
