### ISSUE TITLE
Provide build repository

### ISSUE THREAD

**Issue by Zach677** [Lakr233/NotchDrop#38]
Can I provide my build repository, as well as my private homebrew repository for everyone to use?

If you not allow this, plz tell me. and I will delete link.

NotchDrop release: https://github.com/Zach677/NotchDrop

Homebrew-star: https://github.com/Zach677/homebrew-star

> [!WARNING]
This build project is disabled signing certificate
(https://github.com/Zach677/NotchDrop/blob/0f5a4ecc7f69f97f5c62572014adeb3a1154c38e/.github/workflows/build.yml#L35)

**Comment by Lakr233** [comment]
First of all, someone has already done this.

Secondly, I’ve licensed this software under the MIT License. You’re allowed to distribute the binary as long as you comply with the license terms.

Since this isn’t an issue, I’ll close it now. Thanks for your contribution.
