### ISSUE TITLE
[Error] Airdrop is not available

### ISSUE THREAD

**Issue by PeterWrighten** [Lakr233/NotchDrop#4]
Notch Drop's is not working on my machine(Macbook Pro 2021, M1Pro), and is reports an error as title stated.

<img width="267" alt="Screenshot 2024-07-08 at 6 16 47 PM" src="https://github.com/Lakr233/NotchDrop/assets/45826386/0378ab6a-78ab-47b8-adcb-e3904a6c527b">

**Comment by Lakr233** [comment]
I have no idea about this error. Your system returns nothing when calling `NSSharingService(named: .sendViaAirDrop)`.

**Comment by PeterWrighten** [comment]
> I have no idea about this error. Your system returns nothing when calling `NSSharingService(named: .sendViaAirDrop)`.

Got it. Is it caused by Permission and Security issues? I mean if it is, maybe I can fix it somehow.

**Comment by Lakr233** [comment]
Probably, have a look and fire a PR if you made to fix it. :)

**Comment by tageniu** [comment]
I have the same problem previously and I believe it is a permission issue. If NotchDrop is not granted access to Desktop folder then dropping any Desktop file to it will cause this problem. An additional permission check should be added for these special folders.

**Comment by Lakr233** [comment]
Fixed since App Sandbox enabled after #12d1d93
