### ISSUE TITLE
看下新版本是不是修好了这个问题

### ISSUE THREAD

**Issue by Balllbing** [Lakr233/NotchDrop#42]
看下新版本是不是修好了这个问题

_Originally posted by @Lakr233 in https://github.com/Lakr233/NotchDrop/issues/25#issuecomment-2262146930_
            很遗憾，我测试了两天 似乎没有得到改善，依然是有大任务（渲染，打开fcp，关闭fcp，打开lr，关闭lr）过程中触控板仍然会发生震动

**Comment by Vespera-enc** [comment]
Personally, I think that the trackpad vibration effect is a pretty interesting feature, and not a disturbing one. It's an indicator to the user that the application is working properly.

**Comment by Balllbing** [comment]
> Personally, I think that the trackpad vibration effect is a pretty interesting feature, and not a disturbing one. It's an indicator to the user that the application is working properly.

但是事实上这个震动是让人觉得不应该发生的震动，因为他的频率很高并且没有规律you know what i saying
这件事对我产生困扰的原因
1.他会降低我在使用其他软件时的体验
2.我不太清楚他是否会对触控板产生物理损坏（基于上面震动频率的原因，我真不觉得macbook的触控板会有设计这样的震动，但是我确实第一次在macbook上体验到这种反馈）

我会附上一条震动时的视频，大家可以开到最大声听一下这个声音
我能确定的一点是真的在关掉这个程序之后没有出现过这个问题

Uploading 66_1722880984.mp4…

我很真心希望这个只是我的认知错误，希望真的是

**Comment by Balllbing** [comment]
https://github.com/user-attachments/assets/e2de614a-17b0-47db-9955-9779c42a5c5f

**Comment by Lakr233** [comment]
#43 这里有一个新的包 在 App Store 更新前可以试一试 增加了触控板的控制 也许能解决问题

**Comment by Balllbing** [comment]
解决了！！！1
大哥牛逼！
我跪在地上谢谢您！
woc！
真的吊！
他真的不乱震了！！
