### ISSUE TITLE
关于触控板震动和开机自启的问题

### ISSUE THREAD

**Issue by luchenjie** [Lakr233/NotchDrop#43]
开发者您好，

刚从官方商店购买支持了您开发的软件，总体上使用体验很不错，但我认为仍然存在一些需要改进的问题。

首先是在鼠标放在刘海上时，软件的震动问题，有的时候只是无意扫过了刘海就会触发软件的震动，时间长了会觉得有些恼人。并且感觉单次鼠标指针放上去的时候会震动两次而不是一次，请问可以添加一个让用户自定义震动类型的功能嘛？个人觉得不震动或者单次震动的体验会更好。

另一个问题是软件设置开机自启之后，当电脑开机软件第一次加载的时候，会莫名其妙从刘海弹出来一次，请问这个问题可以修复吗？
软件总体上做的很不错，一直在找一款类似的软件，如果上面两个问题可以解决那就完美了。

感谢你的开发与贡献。

**Comment by Lakr233** [comment]
你说的有道理 我过几天看下怎么做比较好

**Comment by Lakr233** [comment]
试试这个版本 App Store 审核还需要好几天的样子。。

[NotchDrop.zip](https://github.com/user-attachments/files/16517831/NotchDrop.zip)

**Comment by luchenjie** [comment]
新版本中，问题已经成功解决了，非常感谢！

**Comment by Lakr233** [comment]
那后面等一下更新哈 我先把 issue 关啦
