### ISSUE TITLE
请求加入“快速查看”功能

### ISSUE THREAD

**Issue by codehz** [Lakr233/NotchDrop#45]
目前的一个问题是顶部展示文件预览的空间太小了，而有时想要预览一下内容，但尝试了一下space无法触发预览，而点击打开的话会启动“预览”app，也不方便在多个条目之间跳转

我建议是加入快速查看的功能，不确定开发者是否方便
参考：
https://developer.apple.com/documentation/quicklookui/qlpreviewpanel

**Comment by Lakr233** [comment]
所以你想把打开文件换成预览吗

我不是很想把一个做了大量减法的产品突然回来开始加功能 建议是你自己做一个

**Comment by codehz** [comment]
确实，所以只是功能请求，如果不在计划内的话就算了
----
是想用空格预览，点击打开，所以看起来确实是加功能了（）
