### ISSUE TITLE
Something wrong when dragging files into WeChat.

### ISSUE THREAD

**Issue by jinquan-shi** [Lakr233/NotchDrop#48]
Hi Lakr233,

Thanks for the awesome tool! It’s super useful for everyday tasks.

I noticed a small issue though. When I drag files into WeChat, the file’s path is shown instead of the confirmation window. Can you please take a look?

Thanks.

Sharing from NotchDrop:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/1cc37a01-d240-417e-8bcd-4392619c99fd">
Share the original file:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/84c00935-9444-435d-b623-bac4cedc9f3a">

**Comment by Lakr233** [comment]
First of all, newer version ships a fix for that. You should try to upgrade or use an App Store version. But I'm not promising a fix.  

Secondly, update WeChat to see if any improvements happens. 

Lastly, if it still ain't work, it is on the WeChat side not loading the file. I was unable to provide fix that requires code change in another app, in this case is the WeChat itself.
