### ISSUE TITLE
You dont have a notch screen

### ISSUE THREAD

**Issue by yetone** [Lakr233/NotchDrop#5]
<img width="328" alt="image" src="https://github.com/Lakr233/NotchDrop/assets/1206493/2307b4a6-e255-43d6-bf2f-55666917a378">

**Comment by Lakr233** [comment]
你看下是不是盖子关上了 这货只允许在内建显示屏上使用

**Comment by yetone** [comment]
明白了，我用的是外接显示器，嘻嘻

**Comment by Lakr233** [comment]
你可以直接改代码 我不太想做多显示器和非刘海屏的支持 ~~除非有人帮我做~~

**Comment by yetone** [comment]
我也太不会了吧

**Comment by Lakr233** [comment]
改了下文案 避免歧义 那我关了哈

**Comment by Lakr233** [comment]
> 我也太不会了吧

其实我的设计是支持多屏幕多刘海的 但是我知道会有用户要开关哪个显示器开哪个显示器关 对于这样的小程序来说 做设置面板的投入产出实在是划不来 让他们付费的产品去做就好了 我是这么想的
