### ISSUE TITLE
文件拖出来后自动复制问题

### ISSUE THREAD

**Issue by Ymriri** [Lakr233/NotchDrop#58]
同一份文件拖出来然后又放回去就自动复制2份了
版本：好像很久以前在推那边引流过来的，现在貌似版本看不到了，不知道是否解决该问题了
以前的用户还可以继续使用吗？

**Comment by Lakr233** [comment]
现在还有 并没有打算修改这个设计

以前的用户依然可以继续使用 没有任何限制

**Comment by Lakr233** [comment]
你要是觉得不好用可以自己修改一份

**Comment by Ymriri** [comment]
后续是闭源了吗？还是只是不发编译好的文件了

**Comment by Lakr233** [comment]
一直都开源 不发编译好的签名好的而已 你看下 readme 好不好
