### ISSUE TITLE
临时文件清空后，文件不显示，但是临时文件夹中的文件还是没有删除。

### ISSUE THREAD

**Issue by weili888** [Lakr233/NotchDrop#60]
我将文件拖动到软件后，然后进入软件设置，清空文件后，软件不显示文件，但是发现临时文件夹中文件并没有删除。还在硬盘中，这个文件每次都需要手动删除吗？

**Comment by Lakr233** [comment]
问问 为什么关闭了呢？

**Comment by Lakr233** [comment]
如果问题还在的话 喊我修
