### ISSUE TITLE
Cannot drag files out of notch

### ISSUE THREAD

**Issue by murphymjosh** [Lakr233/NotchDrop#62]
When I try to drag a file out of the tray it wont paste anywhere

https://share.cleanshot.com/63BH1Wc7

**Comment by Lakr233** [comment]
Sorry for the inconvenience, a fix is pushed.

**Comment by Lakr233** [comment]
I have requested an urgent App Store review, which should be completed by tomorrow.

This seems to be a new API compatibility issue. The workaround for now is to temporarily copy the drop item.

**Comment by murphymjosh** [comment]
Awesome, thanks!

**Comment by Lakr233** [comment]
Apple has approved my submission, you should be able to update now.
