### ISSUE TITLE
A tiny zone at the top of notch can not click to open.

### ISSUE THREAD

**Issue by Tackoil** [Lakr233/NotchDrop#8]
https://github.com/Lakr233/NotchDrop/assets/24915252/254b2ac3-ae1a-4f10-bcb3-c45e1c263eb4

There is a tiny dead zone in the notch, and I cannot open the app when clicking this zone. Thus I cannot just push the mouse to the top and click to open it. It'll be a little bit inconvenient. 

- Macbook Air M2, 2022 - 13inch
- macOS 15.0-beta.2

**Comment by Lakr233** [comment]
Might be able to fix by extending deviceNotchRect a little bit. Gonna check it later.
