### ISSUE TITLE
Cannot use with an external display.

### ISSUE THREAD

**Issue by laipz8200** [Lakr233/NotchDrop#9]
If I connect an external display(above my MacBook), it is like this:

https://github.com/Lakr233/NotchDrop/assets/16485841/bd7dd698-9bdc-4b2a-92db-b93ab8bf92d6

**Comment by HansonChan** [comment]
> If I connect an external display(above my MacBook), it is like this:
> 
>  Screen.Recording.2024-07-09.at.1.04.03.AM.mov

same problem

**Comment by Lakr233** [comment]
I am unable to reproduce this issue using 1.1.10. I would kindly ask you to upgrade NotchDrop. If the issue still exists, come back and reopen it! :)

https://github.com/Lakr233/NotchDrop/assets/25259084/3a860cd6-f5ed-45e2-8f73-5be72ef5e708

**Comment by laipz8200** [comment]
Hi @Lakr233!

It seems I don't have permission to reopen this issue. I upgraded to version 1.1.11, but the problem persists. After doing a few tests, I've found that it only occurs when the built-in display is not set as the main display.

Thank you for your assistance!

**Comment by Lakr233** [comment]
I'll get back to you when I fix it.

**Comment by Kyle-Ye** [comment]
I reproduced this issue locally. And looks like the logic is here.

<img width="1504" alt="image" src="https://github.com/Lakr233/NotchDrop/assets/43724855/ac5302b4-688c-456e-817f-96e1a48bd7c3">

**Comment by ipf-shkim** [comment]
it can simply fix by calculate x and y frame 

NotchViewModel line 49
```swift
var notchOpenedRect: CGRect {
        .init(
            x: screenRect.width / 2 - notchOpenedSize.width / 2 + screenRect.minX,
            y: screenRect.height - notchOpenedSize.height + screenRect.minY,
            width: notchOpenedSize.width,
            height: notchOpenedSize.height
        )
    }
```

**Comment by tkgka** [comment]
it can simply fix by calculate x and y frame 

NotchViewModel line 49
```swift
var notchOpenedRect: CGRect {
        .init(
            x: screenRect.width / 2 - notchOpenedSize.width / 2 + screenRect.minX,
            y: screenRect.height - notchOpenedSize.height + screenRect.minY,
            width: notchOpenedSize.width,
            height: notchOpenedSize.height
        )
    }
```
